version: 2.1
jobs:
  build-frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Build Frontend"
          command: |
             cd frontend
             npm install
             npm run build
  
  build-backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: "Build Backend"
          command: |
              cd backend
              npm install
              npm run build

# Invoke jobs via workflows
workflows:
  default:
    jobs:
      - build-frontend
      - build-backend
